Global:
  use_gpu: true
  epoch_num: 150
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./Adam/output/rec/common_b
  save_epoch_step: 60
  # evaluation is run every 2000 iterations after the 0th iteration
  eval_batch_step: [0, 1000]
  cal_metric_during_train: True
  pretrained_model: ./Adam/pretrain/ch_ppocr_server_v2.0_rec_pre/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: ./doc/imgs_words/ch/word_1.jpg
  # for data or label process
  character_dict_path: ./ppocr/utils/steel_en_dict.txt
  character_type: ch
  max_text_length: 10
  distort: True
  infer_mode: False
  use_space_char: True
  save_res_path: ./Adam/output/rec/common_b/predicts_chinese_common_v2.0.txt


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0.00004

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: ResNet
    layers: 34
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 256
  Head:
    name: CTCHead
    fc_decay: 0.00004

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/drive/MyDrive/t_brain/full_cut_v2
    label_file_list: ["./Adam/train_data/paddle_rec_cut_train_b.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecAug:
          use_tia: True
          aug_prob: 0.4
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 100
    drop_last: True
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/drive/MyDrive/t_brain/testing_cut
    label_file_list: ["./Adam/train_data/paddle_rec_cut_test_b.txt"]
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 320]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 100
    num_workers: 8
